apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ms
  labels:
    app: frontend-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ms
  template:
    metadata:
      labels:
        app: frontend-ms
    spec:
      containers:
      - name: frontend-ms
        image:  islamahmad/eaproj-frontend-ms:1.1.2
        imagePullPolicy: Always
        # env:
        # - name: API_GATEWAY
        #   value: "35.241.22.50"
        # - name: TEST_VAR
        #   value: "test"
        envFrom:
          - configMapRef:
              name: frontend-ms
