apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ms
  labels:
    app: frontend-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ms
  template:
    metadata:
      labels:
        app: frontend-ms
    spec:
      containers:
        - name: frontend-ms
          image:  islamahmad/eaproj-frontend-ms:1.0.2
          env:
            - name: MS_AUTH
              value: http://auth-ms-service.default.svc.cluster.local:8080
            - name: MS_USER
              value: http://user-ms-service.default.svc.cluster.local:8080
            - name: MS_QUESTIONS
              value: http://question-ms-service.default.svc.cluster.local:8080
            - name: MS_ANSWERS
              value: http://answer-ms-service.default.svc.cluster.local:8080
            - name: MS_COMMENTS
              value: http://comment-ms-service.default.svc.cluster.local:8080
            - name: ENVIRONMENT
              value: production1

